name: build-and-test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './BinX Internship/Week 9/Day 3/Cardiac Patient Monitoring System'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore

      - run: dotnet build --no-restore

      - run: dotnet test --no-build

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install -g @railway/cli

      - run: railway up --service "Mohammad-Salameh-BinX-Backend-Internship" --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}